### ISSUE TITLE
Does not pass the URL to applications correctly

### ISSUE THREAD

**Issue by SpyderZT** [Garulf/FlowYouTube#15]
So I was trying to set this up to pass a Youtube link to my media players, and it will reach and launch the player, pass the arguments, but it isn't passing the URL. I tried in Potplayer & VLC. Potplayer just silently fails, but VLC at least provided an Error that shows a hint as to what's happening:

```
Your input can't be opened:
VLC is unable to open the MRL 'file:///C:/Users/matth/AppData/Roaming/FlowLauncher/Plugins/FlowYouTube-2.0.0/lib/certifi/py.typed'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'file:///C:/Users/matth/AppData/Roaming/FlowLauncher/Plugins/FlowYouTube-2.0.0/lib/certifi-2022.9.24.dist-info/INSTALLER'. Check the log for details.

```

It's definitely possible I'm doing something wrong, but I tried launching the same youtube links FlowYouTube found via command line myself and they worked just fine.

**Comment by Garulf** [comment]
Hello @SpyderZT 

Do you have a screenshot of your settings?

For example my setup using potplayer:

https://cdn.discordapp.com/attachments/728570913045479455/1045597847246082098/image.png

**Comment by SpyderZT** [comment]
That would be it, it's working now. I didn't have the {url} argument as I didn't know it needed to be there. ;? I assumed the URL was transparently passed to the application and the arguments were for any additional functionality the user may want such as appending files to a playlist or launching new instances, etc. so I didn't even consider such a thing. If it was auto populated and I deleted it, I'm sorry for wasting your time. -.-

If not though, perhaps including it pre-filled and maybe including a help line below with a formatting example for the arguments line would be helpful? Or maybe a short blurp on the repo landing page / readme explaining the expected formatting, as I assume you're using {url} to allow arguments in front of the URL if the user so chooses. Either way, dopes like me will have this question available to reference in the future at the very least. ;P

Thanks for getting back to me so quickly.

**Comment by Garulf** [comment]
> That would be it, it's working now. I didn't have the {url} argument as I didn't know it needed to be there. ;? I assumed the URL was transparently passed to the application and the arguments were for any additional functionality the user may want such as appending files to a playlist or launching new instances, etc. so I didn't even consider such a thing. If it was auto populated and I deleted it, I'm sorry for wasting your time. -.-
> 

No worries I had coded it with best intentions to auto inject the url as an argument if the setting was left blank. But looking at the code it doesn't behave like that at all. I'll have a fix for this coming when I can.


> If not though, perhaps including it pre-filled and maybe including a help line below with a formatting example for the arguments line would be helpful? Or maybe a short blurp on the repo landing page / readme explaining the expected formatting, as I assume you're using {url} to allow arguments in front of the URL if the user so chooses. Either way, dopes like me will have this question available to reference in the future at the very least. ;P

Originally I had a long description explaining this but Flow's formatting for non-C# plugins is really bad and almost unreadable. This was going to be added to the readme but I haven't had a chance to write it out properly yet.


> Thanks for getting back to me so quickly.

NP :)

Just happy to see people using my plugins!
