### ISSUE TITLE
[Feature Request] Option to copy url to clipboard

### ISSUE THREAD

**Issue by rp1231** [Garulf/FlowYouTube#18]
Sometimes you want to copy the url to the clipboard.

**Comment by Garulf** [comment]
Done! Version 2.1.0 will have this feature!

![image](https://user-images.githubusercontent.com/535299/224939983-ee6861aa-b9cf-40f9-a03f-adb2504a692d.png)

Also you can use the <kbd>ctrl</kbd>+<kbd>C</kbd> keyboard shortcut on a result and copy the video's URL to your clipboard as well.
