### ISSUE TITLE
Not respecting browser preference

### ISSUE THREAD

**Issue by Anu-bhav** [Garulf/FlowYouTube#4]
Hi @Garulf, 

The plugin is not respecting my browser preference that I chose for flow launcher.

Instead it is using my default browser.

**Comment by Anu-bhav** [comment]
Thank you for the awesome plugin once again. I'll wait for the future update. 

Is it possible to optimise it a bit? when using the built in youtube search, the results are almost instant. However the plugins results do take 2-3 seconds to load.

**Comment by Anu-bhav** [comment]
I think I figured out why this is happening. 
You have to enter an exact search term for it to retrieve all the information. 


How about combining the prediction feature of the built in search.
The result was instant as it was already cached.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/41940586/156733748-96af1e68-2422-4360-810c-bd6ff221fc5f.gif)

**Comment by Garulf** [comment]
> I think I figured out why this is happening. 
> 
> You have to enter an exact search term for it to retrieve all the information. 
> 
> 
> 
> 
> 
> How about combining the prediction feature of the built in search.
> 
> The result was instant as it was already cached.
> 
> 
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/41940586/156733748-96af1e68-2422-4360-810c-bd6ff221fc5f.gif)
> 
> 
> 
> 

The built in YouTube search simple pulls up a list of suggestions based on your query and no meta data. One way to really speed up is to turn off thumbnails in the settings menu.

**Comment by Anu-bhav** [comment]
Is it possible to pull suggestions as well? 
Sometimes you don't really know the exact name of the video and it is really useful to get the suggestions while typing.

**Comment by Garulf** [comment]
> Is it possible to pull suggestions as well? Sometimes you don't really know the exact name of the video and it is really useful to get the suggestions while typing.
> 
> I tried turning off thumbnail also. Not much improvement can be seen as I do have a pretty good connection.

Sadly there is no way to give suggestions *AND* search results in one plugin at the moment.

**Comment by Anu-bhav** [comment]
No problem. I usually do not like my miscellaneous searches to be in default browser history. 
 I'll be waiting for next update.

**Comment by Garulf** [comment]
The plugin now respects your custom browser settings set in Flow Launcher!

**Comment by Anu-bhav** [comment]
i've updated. Still not respecting flow browser preference.  
I added MS Edge in private mode to be flow browser and my default browser is chrome.

When i use the plugin, it still opens in chrome.

**Comment by Garulf** [comment]
> i've updated. Still not respecting flow browser preference.  
> 
> I added MS Edge in private mode to be flow browser and my default browser is chrome.
> 
> 
> 
> When i use the plugin, it still opens in chrome.

The only way it would fallback to using the default browser is an error occurred or your results were cached from the previous version. 

Would you mind posting your `plugin.log` located in FlowYouTube's directory? If there was an error it should log it.

**Comment by Anu-bhav** [comment]
Sure. It's saying it can not find edge. 
[plugin.log](https://github.com/Garulf/FlowYouTube/files/8355871/plugin.log)

However flow provides us with a dropdown of installed browser to choose from. And the default link feature opens the link in Edge. I do not have an issue with that.

**Comment by Garulf** [comment]
@Anu-bhav I found the problem! There was a typo in one of the plugins libraries. It has been updated and *should* work now.

**Comment by Anu-bhav** [comment]
I just updated. It is working right now. Thank you for the awesome plugin.
