### ISSUE TITLE
Wrong Language Translation based on IP address

### ISSUE THREAD

**Issue by santiyounger** [Garulf/FlowYouTube#5]
Hi, I love this plugin, unfortunately I'm stuck with a translation issue. I speak English but I'm living in a Spanish speaking country

My YouTube search results are in Spanish 

Here's an example where I search for my own YouTube channel
![image](https://user-images.githubusercontent.com/51902730/157733172-aa6e33fe-30ee-411e-8774-0f51c3f4f0dd.png)

Where the real video's title is in english
![image](https://user-images.githubusercontent.com/51902730/157733386-18664b39-16e8-41af-bb01-b36afca96297.png)

My settings are in English. as well as my whole computer. I've faced issues like this in the past where Google doesn't let me change language and forces me to use my IP address language

Flow Launcher > General
![image](https://user-images.githubusercontent.com/51902730/157732929-1a5807b4-1948-41d4-bd69-96aff0c5caec.png)

However I just changed my VPN to the US to see if that solves it, but it doesn't so my guess is there must be some configuration in this plugin that automatically changes language

as you can see the subtitle under the video is also in spanish (pardon my horrible screenshot hahah)
![ApplicationFrameHost_yeppMJMBVZ](https://user-images.githubusercontent.com/51902730/157734059-3a4919dd-fcaf-445f-bca8-56d41c06481a.png)

It would be awesome to solve this, thanks a lot!

**Comment by Garulf** [comment]
The plugin simply launches youtube.com with your search results and then parses out the results. Whatever language it uses by default is on Googles end (which is weird it still happened with a VPN). 

I'll have to take a look if it's possible to force the language. Thanks for bringing this to my attention and I'm glad you’re enjoying the plugin despite the hiccups.

**Comment by Garulf** [comment]
Okay, I may have found a way to force YouTube to use a different language/location. I'll have to implement and test first however.

**Comment by santiyounger** [comment]
thank you so much for taking a look into it! I'll definitely keep an eye on this, please let me know if you find a way. Really appreciate it, I love this plugin, keep up the awesome work!

**Comment by Garulf** [comment]
Hi @santiyounger !

Sorry for the long delay, implementing these changes in a clean and reasonable way took longer then expected.

If you have Flow Launcher version 1.9.1 or higher please give the latest build a shot by typing this into your Flow Launcher:
```
pm install https://github.com/Garulf/FlowYouTube/releases/download/v0.4.0/FlowYouTube.zip
```

Or refresh you Flow Launcher's Plugin Store and type:
```
pm update flowyoutube
```
It may take some time (about 3 hours) for the newest version to show up on the store however.

**Comment by santiyounger** [comment]
Wow thank you so much for the excellent update

![image](https://user-images.githubusercontent.com/51902730/163243427-b83908d3-bb08-4d6a-ab2c-fdf653f24705.png)

I changed language and location in the settings and now it's working perfectly, showing me results in the desired language!

Really appreciate it, this is definitely my favorite plugin, incredible work! keep it up
